// =========================================================================
// EE TEST REGISTRY
// =========================================================================
// Add quizzes/tests for EE below:


registerTest({
  series: "ee-gate-pyq-2027",
  name: "EE - Electric Circuits -1",
  date: "March 07, 2026",
  questions: [
    {
      marks: 1,
      neg: 0.33,
      type: "MCQ",
      text: `<p> It is required to determine the current through <em>Z </em> by Thevenin ’s theorem. The open circuit impedance measured between <em>A </em> and <em>B </em> is </p> <p> <img src="images/quiz/ee_ec_1/q6_1.png" style="max-width: 100%;"/> </p>`,
      image: "",
      options: [
        `<p>20 Ω</p>`,
        `<p> (5 –5<em>j</em> ) Ω </p>`,
        `<p> (5 + 5<em>j</em> ) Ω </p>`,
        `<p>10 Ω</p>`,
      ],
      answer: "D",
      solution: `<p> <img src="images/quiz/ee_ec_1/q6_sol_2.png" style="max-width: 100%;"/> </p> <p> <img src="images/quiz/ee_ec_1/q6_sol_3.png" style="max-width: 100%;"/> </p>`,
    },
    {
      marks: 1,
      neg: 0.33,
      type: "MCQ",
      text: `<p> <img src="images/quiz/ee_ec_1/q7_1.png" style="max-width: 100%;"/> </p> <p> <img src="images/quiz/ee_ec_1/q7_2.png" style="max-width: 100%;"/> </p>`,
      image: "",
      options: [
        `<p> <img src="images/quiz/ee_ec_1/q7_optA_3.png" style="max-width: 100%;"/> </p>`,
        `<p> <img src="images/quiz/ee_ec_1/q7_optB_4.png" style="max-width: 100%;"/> </p>`,
        `<p> <img src="images/quiz/ee_ec_1/q7_optC_5.png" style="max-width: 100%;"/> </p>`,
        `<p> <img src="images/quiz/ee_ec_1/q7_optD_6.png" style="max-width: 100%;"/> </p>`,
      ],
      answer: "D",
      solution: `<p> <img src="images/quiz/ee_ec_1/q7_sol_7.png" style="max-width: 100%;"/> </p>`,
    },
    {
      marks: 1,
      neg: 0.33,
      type: "MCQ",
      text: `<p> <img src="images/quiz/ee_ec_1/q9_1.png" style="max-width: 100%;"/> </p>`,
      image: "",
      options: [
        `<p> <img src="images/quiz/ee_ec_1/q9_optA_2.png" style="max-width: 100%;"/> </p>`,
        `<p> <img src="images/quiz/ee_ec_1/q9_optB_3.png" style="max-width: 100%;"/> </p>`,
        `<p> <img src="images/quiz/ee_ec_1/q9_optC_4.png" style="max-width: 100%;"/> </p>`,
        `<p> <img src="images/quiz/ee_ec_1/q9_optD_5.png" style="max-width: 100%;"/> </p>`,
      ],
      answer: "C",
      solution: `<p> <img src="images/quiz/ee_ec_1/q9_sol_6.png" style="max-width: 100%;"/> </p> <p> <img src="images/quiz/ee_ec_1/q9_sol_7.png" style="max-width: 100%;"/> </p>`,
    },
    {
      marks: 1,
      neg: 0,
      type: "NAT",
      text: `<p>Consider the following circuit:</p> <p> <img src="images/quiz/ee_ec_1/q11_1.png" style="max-width: 100%;"/> </p> <p> The value of voltage V <em> <sub>x</sub> </em> is ______ V. </p>`,
      image: "",
      options: [],
      answer: [0, 0],
      solution: `<p> <img src="images/quiz/ee_ec_1/q11_sol_2.png" style="max-width: 100%;"/> </p>`,
    },
    {
      marks: 1,
      neg: 0,
      type: "NAT",
      text: `<p>For the circuit shown below,</p> <p> <img src="images/quiz/ee_ec_1/q12_1.png" style="max-width: 100%;"/> </p> <p> <img src="images/quiz/ee_ec_1/q12_2.png" style="max-width: 100%;"/> </p>`,
      image: "",
      options: [],
      answer: [4.25, 4.29],
      solution: `<p> <img src="images/quiz/ee_ec_1/q12_sol_3.png" style="max-width: 100%;"/> </p> <p> <img src="images/quiz/ee_ec_1/q12_sol_4.png" style="max-width: 100%;"/> </p> <p> <img src="images/quiz/ee_ec_1/q12_sol_5.png" style="max-width: 100%;"/> </p>`,
    },
    {
      marks: 1,
      neg: 0,
      type: "NAT",
      text: `<p>Consider the circuit shown below:</p> <p> <img src="images/quiz/ee_ec_1/q14_1.png" style="max-width: 100%;"/> </p> <p> The voltage V <sub> <em>x</em> </sub> is _________ V. (Answer round off to nearest integer) </p>`,
      image: "",
      options: [],
      answer: [174, 176],
      solution: `<p> <img src="images/quiz/ee_ec_1/q14_sol_2.png" style="max-width: 100%;"/> </p>`,
    },
    {
      marks: 1,
      neg: 0,
      type: "NAT",
      text: `<p>Consider the circuit shown below:</p> <p> <img src="images/quiz/ee_ec_1/q15_1.png" style="max-width: 100%;"/> </p> <p> The value of resistance <em>R</em> , so that the energy stored in the inductor is equal to the energy stored in the capacitor at steady state is ________ Ω. </p>`,
      image: "",
      options: [],
      answer: [100, 100],
      solution: `<p> <img src="images/quiz/ee_ec_1/q15_sol_2.png" style="max-width: 100%;"/> </p>`,
    },
    {
      marks: 1,
      neg: 0,
      type: "NAT",
      text: `<p>Two inductors connected in parallel are equivalent to a single inductance of 1.5 H, and when connected in series are equivalent to a single inductance of 8 H. The difference in their inductance is ______H. (Neglect the mutual inductance)</p>`,
      image: "",
      options: [],
      answer: [4, 4],
      solution: `<p> <img src="images/quiz/ee_ec_1/q16_sol_1.png" style="max-width: 100%;"/> </p>`,
    },
    {
      marks: 1,
      neg: 0.33,
      type: "MCQ",
      text: `<p>The capacitors (C) are arranged as shown in figure below, to obtain a capacitance value of 4 μF rated for 900 V.</p> <p> <img src="images/quiz/ee_ec_1/q17_1.png" style="max-width: 100%;"/> </p> <p>The maximum charge stored by a capacitor is</p>`,
      image: "",
      options: [
        `<p>3.6 mC</p>`,
        `<p>1.2 mC</p>`,
        `<p>2.2 mC</p>`,
        `<p>2.4 mC</p>`,
      ],
      answer: "B",
      solution: `<p> <img src="images/quiz/ee_ec_1/q17_sol_2.png" style="max-width: 100%;"/> </p> <p> <img src="images/quiz/ee_ec_1/q17_sol_3.png" style="max-width: 100%;"/> </p> <p> <img src="images/quiz/ee_ec_1/q17_sol_4.png" style="max-width: 100%;"/> </p>`,
    },
    {
      marks: 2,
      neg: 0,
      type: "NAT",
      text: `<p>The power factor for the circuit shown below is _____ (leading). (Upto three decimal places)</p> <p> <img src="images/quiz/ee_ec_1/q1_1.png" style="max-width: 100%;"/> </p> <p> </p>`,
      image: "",
      options: [],
      answer: [0.97, 0.985],
      solution: `<p> <img src="images/quiz/ee_ec_1/q1_sol_2.png" style="max-width: 100%;"/> </p> <p> <img src="images/quiz/ee_ec_1/q1_sol_3.png" style="max-width: 100%;"/> </p> <p> <img src="images/quiz/ee_ec_1/q1_sol_4.png" style="max-width: 100%;"/> </p>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p> A resistor <em>R </em> in series with a capacitance <em>C </em> is connected to a 240 V-50 Hz ac apply. The value of <em>C </em> so that <em>R </em> absorbs 150 W at 50 V is </p>`,
      image: "",
      options: [
        `<p> <img src="images/quiz/ee_ec_1/q2_optA_1.png" style="max-width: 100%;"/> </p>`,
        `<p> <img src="images/quiz/ee_ec_1/q2_optB_2.png" style="max-width: 100%;"/> </p>`,
        `<p> <img src="images/quiz/ee_ec_1/q2_optC_3.png" style="max-width: 100%;"/> </p>`,
        `<p> <img src="images/quiz/ee_ec_1/q2_optD_4.png" style="max-width: 100%;"/> </p>`,
      ],
      answer: "C",
      solution: `<p> <img src="images/quiz/ee_ec_1/q2_sol_5.png" style="max-width: 100%;"/> </p> <p> <img src="images/quiz/ee_ec_1/q2_sol_6.png" style="max-width: 100%;"/> </p>`,
    },
    {
      marks: 2,
      neg: 0,
      type: "NAT",
      text: `<p>Consider the following circuit:</p> <p> <img src="images/quiz/ee_ec_1/q3_1.png" style="max-width: 100%;"/> </p> <p> the maximum average power draws by the load Z<sub>L</sub> is ________ W. </p>`,
      image: "",
      options: [],
      answer: [4.65, 4.8],
      solution: `<p> <img src="images/quiz/ee_ec_1/q3_sol_2.png" style="max-width: 100%;"/> </p> <p> <img src="images/quiz/ee_ec_1/q3_sol_3.png" style="max-width: 100%;"/> </p> <p> <img src="images/quiz/ee_ec_1/q3_sol_4.png" style="max-width: 100%;"/> </p>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p>Consider the following circuit:</p> <p> <img src="images/quiz/ee_ec_1/q4_1.png" style="max-width: 100%;"/> </p> <p> <img src="images/quiz/ee_ec_1/q4_2.png" style="max-width: 100%;"/> </p>`,
      image: "",
      options: [
        `<p> <img src="images/quiz/ee_ec_1/q4_optA_3.png" style="max-width: 100%;"/> </p>`,
        `<p> <img src="images/quiz/ee_ec_1/q4_optB_4.png" style="max-width: 100%;"/> </p>`,
        `<p> <img src="images/quiz/ee_ec_1/q4_optC_5.png" style="max-width: 100%;"/> </p>`,
        `<p> <img src="images/quiz/ee_ec_1/q4_optD_6.png" style="max-width: 100%;"/> </p>`,
      ],
      answer: "A",
      solution: `<p> <img src="images/quiz/ee_ec_1/q4_sol_7.png" style="max-width: 100%;"/> </p> <p> <img src="images/quiz/ee_ec_1/q4_sol_8.png" style="max-width: 100%;"/> </p> <p> <img src="images/quiz/ee_ec_1/q4_sol_9.png" style="max-width: 100%;"/> </p> <p> <img src="images/quiz/ee_ec_1/q4_sol_10.png" style="max-width: 100%;"/> </p> <p> <img src="images/quiz/ee_ec_1/q4_sol_11.png" style="max-width: 100%;"/> </p> <p> </p> <p> <img src="images/quiz/ee_ec_1/q4_sol_12.png" style="max-width: 100%;"/> </p> <p> <img src="images/quiz/ee_ec_1/q4_sol_13.png" style="max-width: 100%;"/> </p>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p> In the circuit shown in figure ‘<em>X</em> ’is an element which always absorbs power. During a particular operation, it sets up a current of 1 amp in the direction shown and absorbs a power <em> P<sub>X</sub> </em> . It is possible that ‘<em>X</em> ’can absorb the same power <em> P<sub>X</sub> </em> for another current i, the value of this current is </p> <p> <img src="images/quiz/ee_ec_1/q5_1.png" style="max-width: 100%;"/> </p>`,
      image: "",
      options: [
        `<p> <img src="images/quiz/ee_ec_1/q5_optA_2.png" style="max-width: 100%;"/> </p>`,
        `<p> <img src="images/quiz/ee_ec_1/q5_optB_3.png" style="max-width: 100%;"/> </p>`,
        `<p> <img src="images/quiz/ee_ec_1/q5_optC_4.png" style="max-width: 100%;"/> </p>`,
        `<p> <img src="images/quiz/ee_ec_1/q5_optD_5.png" style="max-width: 100%;"/> </p>`,
      ],
      answer: "D",
      solution: `<p> <img src="images/quiz/ee_ec_1/q5_sol_6.png" style="max-width: 100%;"/> </p>`,
    },
    {
      marks: 2,
      neg: 0,
      type: "NAT",
      text: `<p>Consider the circuit shown below:</p> <p> <img src="images/quiz/ee_ec_1/q8_1.png" style="max-width: 100%;"/> </p> <p>The power delivered by the unknown element is ________ W.</p>`,
      image: "",
      options: [],
      answer: [421, 425],
      solution: `<p> <img src="images/quiz/ee_ec_1/q8_sol_2.png" style="max-width: 100%;"/> </p> <p> <img src="images/quiz/ee_ec_1/q8_sol_3.png" style="max-width: 100%;"/> </p>`,
    },
    {
      marks: 2,
      neg: 0,
      type: "MSQ",
      text: `<p>Consider the circuit shown below:</p> <p> <img src="images/quiz/ee_ec_1/q10_1.png" style="max-width: 100%;"/> </p> <p>Which of the following is/are correct?</p>`,
      image: "",
      options: [
        `<p> <img src="images/quiz/ee_ec_1/q10_optA_2.png" style="max-width: 100%;"/> </p>`,
        `<p> <img src="images/quiz/ee_ec_1/q10_optB_3.png" style="max-width: 100%;"/> </p>`,
        `<p> <img src="images/quiz/ee_ec_1/q10_optC_4.png" style="max-width: 100%;"/> </p>`,
        `<p> <img src="images/quiz/ee_ec_1/q10_optD_5.png" style="max-width: 100%;"/> </p>`,
      ],
      answer: ["B", "A", "C"],
      solution: `<p> <img src="images/quiz/ee_ec_1/q10_sol_6.png" style="max-width: 100%;"/> </p> <p> <img src="images/quiz/ee_ec_1/q10_sol_7.png" style="max-width: 100%;"/> </p>`,
    },
    {
      marks: 2,
      neg: 0,
      type: "NAT",
      text: `<p>For the circuit shown below:</p> <p> <img src="images/quiz/ee_ec_1/q13_1.png" style="max-width: 100%;"/> </p> <p> <img src="images/quiz/ee_ec_1/q13_2.png" style="max-width: 100%;"/> </p>`,
      image: "",
      options: [],
      answer: [64, 65.8],
      solution: `<p> <img src="images/quiz/ee_ec_1/q13_sol_3.png" style="max-width: 100%;"/> </p>`,
    },
  ]
})

registerTest({
  series: "ee-gate-pyq-2027",
  name: "EE - Electric Circuits -2",
  date: "March 07, 2026",
  questions: [
    {
      marks: 1,
      neg: 0.33,
      type: "MCQ",
      text: `<p>Three identical resistance are connected in a star fashion against a balanced three phase voltage supply. If one of the resistances be removed then the percentage reduction in power is</p>`,
      image: "",
      options: [
        `<p>17.32%</p>`,
        `<p>33.33%</p>`,
        `<p>14.14%</p>`,
        `<p>50%</p>`,
      ],
      answer: "D",
      solution: `<p> <img src="images/quiz/ee_ec_2/q3_sol_1.png" style="max-width: 100%;"/> </p>`,
    },
    {
      marks: 1,
      neg: 0,
      type: "NAT",
      text: `<p> A series R-L-C circuit has following parameters, <em>R </em> = 10 Ω, <em>L </em> = 0.01 H and <em>C </em> = 100 μF. The upper 3 dB frequency of the circuit is _________ Hz. (upto two decimal places) </p>`,
      image: "",
      options: [],
      answer: [255.21, 258.5],
      solution: `<p> <img src="images/quiz/ee_ec_2/q8_sol_1.png" style="max-width: 100%;"/> </p> <p> <img src="images/quiz/ee_ec_2/q8_sol_2.png" style="max-width: 100%;"/> </p>`,
    },
    {
      marks: 1,
      neg: 0.33,
      type: "MCQ",
      text: `<p> The z-parameter Z<sub>22</sub> for the two port network shown below is </p> <p> <img src="images/quiz/ee_ec_2/q9_1.png" style="max-width: 100%;"/> </p>`,
      image: "",
      options: [
        `<p> <img src="images/quiz/ee_ec_2/q9_optA_2.png" style="max-width: 100%;"/> </p>`,
        `<p> <img src="images/quiz/ee_ec_2/q9_optB_3.png" style="max-width: 100%;"/> </p>`,
        `<p> <img src="images/quiz/ee_ec_2/q9_optC_4.png" style="max-width: 100%;"/> </p>`,
        `<p> <img src="images/quiz/ee_ec_2/q9_optD_5.png" style="max-width: 100%;"/> </p>`,
      ],
      answer: "B",
      solution: `<p> <img src="images/quiz/ee_ec_2/q9_sol_6.png" style="max-width: 100%;"/> </p> <p> <img src="images/quiz/ee_ec_2/q9_sol_7.png" style="max-width: 100%;"/> </p>`,
    },
    {
      marks: 1,
      neg: 0.33,
      type: "MCQ",
      text: `<p>For the tank circuit shown in figure below, the resonant frequency is</p> <p> <img src="images/quiz/ee_ec_2/q10_1.png" style="max-width: 100%;"/> </p> <p> </p>`,
      image: "",
      options: [
        `<p>158.35 Hz</p>`,
        `<p>138.35 Hz</p>`,
        `<p>148.35 Hz</p>`,
        `<p>128.35 Hz</p>`,
      ],
      answer: "A",
      solution: `<p> <img src="images/quiz/ee_ec_2/q10_sol_2.png" style="max-width: 100%;"/> </p>`,
    },
    {
      marks: 1,
      neg: 0.33,
      type: "MCQ",
      text: `<p>Consider the following bridge of T network.</p> <p> <img src="images/quiz/ee_ec_2/q12_1.png" style="max-width: 100%;"/> </p> <p> The <em>z </em> parameters are </p>`,
      image: "",
      options: [
        `<p> <img src="images/quiz/ee_ec_2/q12_optA_2.png" style="max-width: 100%;"/> </p>`,
        `<p> <img src="images/quiz/ee_ec_2/q12_optB_3.png" style="max-width: 100%;"/> </p>`,
        `<p> <img src="images/quiz/ee_ec_2/q12_optC_4.png" style="max-width: 100%;"/> </p>`,
        `<p> <img src="images/quiz/ee_ec_2/q12_optD_5.png" style="max-width: 100%;"/> </p>`,
      ],
      answer: "A",
      solution: `<p> <img src="images/quiz/ee_ec_2/q12_sol_6.png" style="max-width: 100%;"/> </p> <p> <img src="images/quiz/ee_ec_2/q12_sol_7.png" style="max-width: 100%;"/> </p>`,
    },
    {
      marks: 1,
      neg: 0.33,
      type: "MCQ",
      text: `<p> For the circuit shown below, if <em>i </em> = 8 cos 500<em>t</em> A in the network, the total energy stored in the network is ‘<em>x ’</em> Joules. </p> <p> <img src="images/quiz/ee_ec_2/q14_1.png" style="max-width: 100%;"/> </p> <p>For storing same amount of energy, the circuit we can use is</p>`,
      image: "",
      options: [
        `<p> <img src="images/quiz/ee_ec_2/q14_optA_2.png" style="max-width: 100%;"/> </p>`,
        `<p> <img src="images/quiz/ee_ec_2/q14_optB_3.png" style="max-width: 100%;"/> </p>`,
        `<p> <img src="images/quiz/ee_ec_2/q14_optC_4.png" style="max-width: 100%;"/> </p>`,
        `<p> <img src="images/quiz/ee_ec_2/q14_optD_5.png" style="max-width: 100%;"/> </p>`,
      ],
      answer: "C",
      solution: `<p> <img src="images/quiz/ee_ec_2/q14_sol_6.png" style="max-width: 100%;"/> </p>`,
    },
    {
      marks: 1,
      neg: 0.33,
      type: "MCQ",
      text: `<p> For the circuit shown, the switch is closes at <em>t </em> = 0 (after having been open for a very long time).<br/> The current <em>i</em> (<em>t</em> ) is given by (for <em>t </em> ≥0): </p> <p> <img src="images/quiz/ee_ec_2/q15_1.png" style="max-width: 100%;"/> </p>`,
      image: "",
      options: [
        `<p> <img src="images/quiz/ee_ec_2/q15_optA_2.png" style="max-width: 100%;"/> </p>`,
        `<p> <img src="images/quiz/ee_ec_2/q15_optB_3.png" style="max-width: 100%;"/> </p>`,
        `<p> <img src="images/quiz/ee_ec_2/q15_optC_4.png" style="max-width: 100%;"/> </p>`,
        `<p> <img src="images/quiz/ee_ec_2/q15_optD_5.png" style="max-width: 100%;"/> </p>`,
      ],
      answer: "D",
      solution: `<p> Since the switch was open for a long time, the capacitor was initially discharged. After the switch is closed, the capacitor looks initially like a short circuit thus drawing a current of 1 mA. As time progresses the capacitor charges and thus approaches an open circuit so that <em>i</em> (∞) = 0. <br/> The RC time constant is obtained from the two 20 k Ωresistors in parallel and the 10 μF capacitor, or RC = 10<sup>–1</sup> sec. </p> <p> <img src="images/quiz/ee_ec_2/q15_sol_6.png" style="max-width: 100%;"/> </p>`,
    },
    {
      marks: 1,
      neg: 0,
      type: "MSQ",
      text: `<p>Consider the given circuit:</p> <p> <img src="images/quiz/ee_ec_2/q16_1.png" style="max-width: 100%;"/> </p> <p>If the circuit is intitially relaxed, then which of the following option(s) is/are correct?</p>`,
      image: "",
      options: [
        `<p> <img src="images/quiz/ee_ec_2/q16_optA_2.png" style="max-width: 100%;"/> </p>`,
        `<p> <img src="images/quiz/ee_ec_2/q16_optB_3.png" style="max-width: 100%;"/> </p>`,
        `<p> <img src="images/quiz/ee_ec_2/q16_optC_4.png" style="max-width: 100%;"/> </p>`,
        `<p> <img src="images/quiz/ee_ec_2/q16_optD_5.png" style="max-width: 100%;"/> </p>`,
      ],
      answer: ["B", "D"],
      solution: `<p> <img src="images/quiz/ee_ec_2/q16_sol_6.png" style="max-width: 100%;"/> </p> <p> <img src="images/quiz/ee_ec_2/q16_sol_7.png" style="max-width: 100%;"/> </p>`,
    },
    {
      marks: 1,
      neg: 0.33,
      type: "MCQ",
      text: `<p>Consider the following circuit:</p> <p> <img src="images/quiz/ee_ec_2/q17_1.png" style="max-width: 100%;"/> </p> <p> If switch <em>S </em> is closed at <em>t </em> = 0, then current ‘<em>i</em> ’through the battery at <em>t </em> = 0<sup>+</sup> and <em>t</em> = ∞are respectively: </p>`,
      image: "",
      options: [
        `<p>4.5 A and 4.5 A</p>`,
        `<p>4.5 A and 0 A</p>`,
        `<p>0 A and 4.5 A</p>`,
        `<p>2.5 A and 4.5 A</p>`,
      ],
      answer: "A",
      solution: `<p> At <em>t </em> = 0<sup>+</sup> , inductor is open but capacitor is shorted and at t = infinity capacitor is open inductor is shorted.<br/>So, at both times </p> <p> <img src="images/quiz/ee_ec_2/q17_sol_2.png" style="max-width: 100%;"/> </p>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p> In the following figure is shown a network in which a steady state is reached with switch K open.<br/> At <em>t </em> = 0, the switch is closed. For the element given, </p> <p> <img src="images/quiz/ee_ec_2/q1_1.png" style="max-width: 100%;"/> </p> <p> The value of V<sub>a</sub> (0<sup>–</sup> ) and V<sub>a</sub> (0<sup>+</sup> ) are respectively: </p>`,
      image: "",
      options: [
        `<p>5 V and 3 V respectively</p>`,
        `<p>2 V and 3 V respectively</p>`,
        `<p>3 V and 5 V respectively</p>`,
        `<p>2 V and 5 V respectively</p>`,
      ],
      answer: "A",
      solution: `<p> <img src="images/quiz/ee_ec_2/q1_sol_2.png" style="max-width: 100%;"/> </p>`,
    },
    {
      marks: 2,
      neg: 0,
      type: "NAT",
      text: `<p>Consider the following circuit:</p> <p> <img src="images/quiz/ee_ec_2/q2_1.png" style="max-width: 100%;"/> </p> <p>The resonant frequency of the circuit is _________ rad/sec.</p>`,
      image: "",
      options: [],
      answer: [0.5, 0.5],
      solution: `<p> <img src="images/quiz/ee_ec_2/q2_sol_2.png" style="max-width: 100%;"/> </p> <p> <img src="images/quiz/ee_ec_2/q2_sol_3.png" style="max-width: 100%;"/> </p>`,
    },
    {
      marks: 2,
      neg: 0,
      type: "NAT",
      text: `<p> A series circuit consists of 2 Ωresistor, 0.01 H inductor and a capacitor ‘<em>C</em> ’across 200-V mains.<br/> Assume the above series circuit resonates at 50 Hz frequency, then the value of voltage across capacitor ‘<em>C</em> ’at resonance is (in magnitude) _________ V. (upto two decimal places) </p>`,
      image: "",
      options: [],
      answer: [312, 316],
      solution: `<p> <img src="images/quiz/ee_ec_2/q4_sol_1.png" style="max-width: 100%;"/> </p>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p>For the below given network,</p> <p> <img src="images/quiz/ee_ec_2/q5_1.png" style="max-width: 100%;"/> </p> <p>Which of the following is correct?</p>`,
      image: "",
      options: [
        `<p>Network is symmetrical but not reciprocal.</p>`,
        `<p>Network is not symmetrical but reciprocal</p>`,
        `<p>Network is not symmetrical and not reciprocal</p>`,
        `<p>Network is symmetrical as well as reciprocal.</p>`,
      ],
      answer: "B",
      solution: `<p> <img src="images/quiz/ee_ec_2/q5_sol_2.png" style="max-width: 100%;"/> </p> <p> <img src="images/quiz/ee_ec_2/q5_sol_3.png" style="max-width: 100%;"/> </p>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p> <img src="images/quiz/ee_ec_2/q6_1.png" style="max-width: 100%;"/> </p>`,
      image: "",
      options: [
        `<p> <img src="images/quiz/ee_ec_2/q6_optA_2.png" style="max-width: 100%;"/> </p>`,
        `<p> <img src="images/quiz/ee_ec_2/q6_optB_3.png" style="max-width: 100%;"/> </p>`,
        `<p> <img src="images/quiz/ee_ec_2/q6_optC_4.png" style="max-width: 100%;"/> </p>`,
        `<p> <img src="images/quiz/ee_ec_2/q6_optD_5.png" style="max-width: 100%;"/> </p>`,
      ],
      answer: "A",
      solution: `<p> <img src="images/quiz/ee_ec_2/q6_sol_6.png" style="max-width: 100%;"/> </p> <p> <img src="images/quiz/ee_ec_2/q6_sol_7.png" style="max-width: 100%;"/> </p>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p> In the network shown in figure below, at <em>t </em> = 0, the switch is opened. </p> <p> <img src="images/quiz/ee_ec_2/q7_1.png" style="max-width: 100%;"/> </p>`,
      image: "",
      options: [
        `<p>100 MV</p>`,
        `<p>10 kV</p>`,
        `<p>1 MV</p>`,
        `<p>–1 MV</p>`,
      ],
      answer: "A",
      solution: `<p> At <em>t</em> = 0<sup>–</sup> , the switch is closed. Hence, no current flows through the inductor. </p> <p> <img src="images/quiz/ee_ec_2/q7_sol_2.png" style="max-width: 100%;"/> </p> <p> At <em>t</em> = 0<sup>+</sup> , the uncharged inductor acts as open circuit. </p> <p> <img src="images/quiz/ee_ec_2/q7_sol_3.png" style="max-width: 100%;"/> </p> <p> <img src="images/quiz/ee_ec_2/q7_sol_4.png" style="max-width: 100%;"/> </p> <p> <img src="images/quiz/ee_ec_2/q7_sol_5.png" style="max-width: 100%;"/> </p>`,
    },
    {
      marks: 2,
      neg: 0,
      type: "NAT",
      text: `<p>Consider the given Star-Delta pair shown below:</p> <p> <img src="images/quiz/ee_ec_2/q11_1.png" style="max-width: 100%;"/> </p> <p> If <em> C<sub>x</sub> </em> and <em> C<sub>y</sub> </em> are connected in parallel across a 10 cos ω<em>t </em> V supply, then the energy stored by the circuit is _______ (mJ). (Answer upto two decimal places) </p>`,
      image: "",
      options: [],
      answer: [0.4, 0.45],
      solution: `<p> <img src="images/quiz/ee_ec_2/q11_sol_2.png" style="max-width: 100%;"/> </p> <p> <img src="images/quiz/ee_ec_2/q11_sol_3.png" style="max-width: 100%;"/> </p> <p> <img src="images/quiz/ee_ec_2/q11_sol_4.png" style="max-width: 100%;"/> </p>`,
    },
    {
      marks: 2,
      neg: 0,
      type: "MSQ",
      text: `<p>Consider the circuit shown below:</p> <p> <img src="images/quiz/ee_ec_2/q13_1.png" style="max-width: 100%;"/> </p> <p> The inductors and capacitors do not contain any stored energy. If the switch is closed at time <em>t </em> = 0, then which of the following options is/are correct? </p>`,
      image: "",
      options: [
        `<p> Voltage across 6 H inductor is 150 V at <em>t </em> = 0<sup>+</sup> . </p>`,
        `<p> Voltage across 8 H inductor is 75 V at <em>t</em> = 0<sup>+</sup> . </p>`,
        `<p> Voltage across 4 F capacitor is 85.71 V at <em>t</em> = ∞. </p>`,
        `<p> Voltage across 5 F capacitor is 142.85 V at <em>t</em> = ∞. </p>`,
      ],
      answer: ["C", "A", "B", "D"],
      solution: `<p> <img src="images/quiz/ee_ec_2/q13_sol_2.png" style="max-width: 100%;"/> </p>`,
    },
  ]
})
