// =========================================================================
// EE TEST REGISTRY
// =========================================================================
// Add quizzes/tests for EE below:


registerTest({
  series: "ee-gate-pyq-2027",
  name: "EE - ",
  date: "March 07, 2026",
  questions: [
  ]
});

registerTest({
  series: "ee-gate-pyq-2027",
  name: "EE - Electric Circuits -1",
  date: "March 07, 2026",
  questions: [
    {
      marks: 1,
      neg: 0.33,
      type: "MCQ",
      text: `<p> It is required to determine the current through <em>Z </em> by Thevenin ’s theorem. The open circuit impedance measured between <em>A </em> and <em>B </em> is </p> <p> <img src="images/quiz/ee_ec_1/q6_1.png" style="max-width: 100%;"/> </p>`,
      image: "",
      options: [
        `<p>20 Ω</p>`,
        `<p> (5 –5<em>j</em> ) Ω </p>`,
        `<p> (5 + 5<em>j</em> ) Ω </p>`,
        `<p>10 Ω</p>`,
      ],
      answer: "D",
      solution: `<p> <img src="images/quiz/ee_ec_1/q6_sol_2.png" style="max-width: 100%;"/> </p> <p> <img src="images/quiz/ee_ec_1/q6_sol_3.png" style="max-width: 100%;"/> </p>`,
    },
    {
      marks: 1,
      neg: 0.33,
      type: "MCQ",
      text: `<p> <img src="images/quiz/ee_ec_1/q7_1.png" style="max-width: 100%;"/> </p> <p> <img src="images/quiz/ee_ec_1/q7_2.png" style="max-width: 100%;"/> </p>`,
      image: "",
      options: [
        `<p> <img src="images/quiz/ee_ec_1/q7_optA_3.png" style="max-width: 100%;"/> </p>`,
        `<p> <img src="images/quiz/ee_ec_1/q7_optB_4.png" style="max-width: 100%;"/> </p>`,
        `<p> <img src="images/quiz/ee_ec_1/q7_optC_5.png" style="max-width: 100%;"/> </p>`,
        `<p> <img src="images/quiz/ee_ec_1/q7_optD_6.png" style="max-width: 100%;"/> </p>`,
      ],
      answer: "D",
      solution: `<p> <img src="images/quiz/ee_ec_1/q7_sol_7.png" style="max-width: 100%;"/> </p>`,
    },
    {
      marks: 1,
      neg: 0.33,
      type: "MCQ",
      text: `<p> <img src="images/quiz/ee_ec_1/q9_1.png" style="max-width: 100%;"/> </p>`,
      image: "",
      options: [
        `<p> <img src="images/quiz/ee_ec_1/q9_optA_2.png" style="max-width: 100%;"/> </p>`,
        `<p> <img src="images/quiz/ee_ec_1/q9_optB_3.png" style="max-width: 100%;"/> </p>`,
        `<p> <img src="images/quiz/ee_ec_1/q9_optC_4.png" style="max-width: 100%;"/> </p>`,
        `<p> <img src="images/quiz/ee_ec_1/q9_optD_5.png" style="max-width: 100%;"/> </p>`,
      ],
      answer: "C",
      solution: `<p> <img src="images/quiz/ee_ec_1/q9_sol_6.png" style="max-width: 100%;"/> </p> <p> <img src="images/quiz/ee_ec_1/q9_sol_7.png" style="max-width: 100%;"/> </p>`,
    },
    {
      marks: 1,
      neg: 0,
      type: "NAT",
      text: `<p>Consider the following circuit:</p> <p> <img src="images/quiz/ee_ec_1/q11_1.png" style="max-width: 100%;"/> </p> <p> The value of voltage V <em> <sub>x</sub> </em> is ______ V. </p>`,
      image: "",
      options: [],
      answer: [0, 0],
      solution: `<p> <img src="images/quiz/ee_ec_1/q11_sol_2.png" style="max-width: 100%;"/> </p>`,
    },
    {
      marks: 1,
      neg: 0,
      type: "NAT",
      text: `<p>For the circuit shown below,</p> <p> <img src="images/quiz/ee_ec_1/q12_1.png" style="max-width: 100%;"/> </p> <p> <img src="images/quiz/ee_ec_1/q12_2.png" style="max-width: 100%;"/> </p>`,
      image: "",
      options: [],
      answer: [4.25, 4.29],
      solution: `<p> <img src="images/quiz/ee_ec_1/q12_sol_3.png" style="max-width: 100%;"/> </p> <p> <img src="images/quiz/ee_ec_1/q12_sol_4.png" style="max-width: 100%;"/> </p> <p> <img src="images/quiz/ee_ec_1/q12_sol_5.png" style="max-width: 100%;"/> </p>`,
    },
    {
      marks: 1,
      neg: 0,
      type: "NAT",
      text: `<p>Consider the circuit shown below:</p> <p> <img src="images/quiz/ee_ec_1/q14_1.png" style="max-width: 100%;"/> </p> <p> The voltage V <sub> <em>x</em> </sub> is _________ V. (Answer round off to nearest integer) </p>`,
      image: "",
      options: [],
      answer: [174, 176],
      solution: `<p> <img src="images/quiz/ee_ec_1/q14_sol_2.png" style="max-width: 100%;"/> </p>`,
    },
    {
      marks: 1,
      neg: 0,
      type: "NAT",
      text: `<p>Consider the circuit shown below:</p> <p> <img src="images/quiz/ee_ec_1/q15_1.png" style="max-width: 100%;"/> </p> <p> The value of resistance <em>R</em> , so that the energy stored in the inductor is equal to the energy stored in the capacitor at steady state is ________ Ω. </p>`,
      image: "",
      options: [],
      answer: [100, 100],
      solution: `<p> <img src="images/quiz/ee_ec_1/q15_sol_2.png" style="max-width: 100%;"/> </p>`,
    },
    {
      marks: 1,
      neg: 0,
      type: "NAT",
      text: `<p>Two inductors connected in parallel are equivalent to a single inductance of 1.5 H, and when connected in series are equivalent to a single inductance of 8 H. The difference in their inductance is ______H. (Neglect the mutual inductance)</p>`,
      image: "",
      options: [],
      answer: [4, 4],
      solution: `<p> <img src="images/quiz/ee_ec_1/q16_sol_1.png" style="max-width: 100%;"/> </p>`,
    },
    {
      marks: 1,
      neg: 0.33,
      type: "MCQ",
      text: `<p>The capacitors (C) are arranged as shown in figure below, to obtain a capacitance value of 4 μF rated for 900 V.</p> <p> <img src="images/quiz/ee_ec_1/q17_1.png" style="max-width: 100%;"/> </p> <p>The maximum charge stored by a capacitor is</p>`,
      image: "",
      options: [
        `<p>3.6 mC</p>`,
        `<p>1.2 mC</p>`,
        `<p>2.2 mC</p>`,
        `<p>2.4 mC</p>`,
      ],
      answer: "B",
      solution: `<p> <img src="images/quiz/ee_ec_1/q17_sol_2.png" style="max-width: 100%;"/> </p> <p> <img src="images/quiz/ee_ec_1/q17_sol_3.png" style="max-width: 100%;"/> </p> <p> <img src="images/quiz/ee_ec_1/q17_sol_4.png" style="max-width: 100%;"/> </p>`,
    },
    {
      marks: 2,
      neg: 0,
      type: "NAT",
      text: `<p>The power factor for the circuit shown below is _____ (leading). (Upto three decimal places)</p> <p> <img src="images/quiz/ee_ec_1/q1_1.png" style="max-width: 100%;"/> </p> <p> </p>`,
      image: "",
      options: [],
      answer: [0.97, 0.985],
      solution: `<p> <img src="images/quiz/ee_ec_1/q1_sol_2.png" style="max-width: 100%;"/> </p> <p> <img src="images/quiz/ee_ec_1/q1_sol_3.png" style="max-width: 100%;"/> </p> <p> <img src="images/quiz/ee_ec_1/q1_sol_4.png" style="max-width: 100%;"/> </p>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p> A resistor <em>R </em> in series with a capacitance <em>C </em> is connected to a 240 V-50 Hz ac apply. The value of <em>C </em> so that <em>R </em> absorbs 150 W at 50 V is </p>`,
      image: "",
      options: [
        `<p> <img src="images/quiz/ee_ec_1/q2_optA_1.png" style="max-width: 100%;"/> </p>`,
        `<p> <img src="images/quiz/ee_ec_1/q2_optB_2.png" style="max-width: 100%;"/> </p>`,
        `<p> <img src="images/quiz/ee_ec_1/q2_optC_3.png" style="max-width: 100%;"/> </p>`,
        `<p> <img src="images/quiz/ee_ec_1/q2_optD_4.png" style="max-width: 100%;"/> </p>`,
      ],
      answer: "C",
      solution: `<p> <img src="images/quiz/ee_ec_1/q2_sol_5.png" style="max-width: 100%;"/> </p> <p> <img src="images/quiz/ee_ec_1/q2_sol_6.png" style="max-width: 100%;"/> </p>`,
    },
    {
      marks: 2,
      neg: 0,
      type: "NAT",
      text: `<p>Consider the following circuit:</p> <p> <img src="images/quiz/ee_ec_1/q3_1.png" style="max-width: 100%;"/> </p> <p> the maximum average power draws by the load Z<sub>L</sub> is ________ W. </p>`,
      image: "",
      options: [],
      answer: [4.65, 4.8],
      solution: `<p> <img src="images/quiz/ee_ec_1/q3_sol_2.png" style="max-width: 100%;"/> </p> <p> <img src="images/quiz/ee_ec_1/q3_sol_3.png" style="max-width: 100%;"/> </p> <p> <img src="images/quiz/ee_ec_1/q3_sol_4.png" style="max-width: 100%;"/> </p>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p>Consider the following circuit:</p> <p> <img src="images/quiz/ee_ec_1/q4_1.png" style="max-width: 100%;"/> </p> <p> <img src="images/quiz/ee_ec_1/q4_2.png" style="max-width: 100%;"/> </p>`,
      image: "",
      options: [
        `<p> <img src="images/quiz/ee_ec_1/q4_optA_3.png" style="max-width: 100%;"/> </p>`,
        `<p> <img src="images/quiz/ee_ec_1/q4_optB_4.png" style="max-width: 100%;"/> </p>`,
        `<p> <img src="images/quiz/ee_ec_1/q4_optC_5.png" style="max-width: 100%;"/> </p>`,
        `<p> <img src="images/quiz/ee_ec_1/q4_optD_6.png" style="max-width: 100%;"/> </p>`,
      ],
      answer: "A",
      solution: `<p> <img src="images/quiz/ee_ec_1/q4_sol_7.png" style="max-width: 100%;"/> </p> <p> <img src="images/quiz/ee_ec_1/q4_sol_8.png" style="max-width: 100%;"/> </p> <p> <img src="images/quiz/ee_ec_1/q4_sol_9.png" style="max-width: 100%;"/> </p> <p> <img src="images/quiz/ee_ec_1/q4_sol_10.png" style="max-width: 100%;"/> </p> <p> <img src="images/quiz/ee_ec_1/q4_sol_11.png" style="max-width: 100%;"/> </p> <p> </p> <p> <img src="images/quiz/ee_ec_1/q4_sol_12.png" style="max-width: 100%;"/> </p> <p> <img src="images/quiz/ee_ec_1/q4_sol_13.png" style="max-width: 100%;"/> </p>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p> In the circuit shown in figure ‘<em>X</em> ’is an element which always absorbs power. During a particular operation, it sets up a current of 1 amp in the direction shown and absorbs a power <em> P<sub>X</sub> </em> . It is possible that ‘<em>X</em> ’can absorb the same power <em> P<sub>X</sub> </em> for another current i, the value of this current is </p> <p> <img src="images/quiz/ee_ec_1/q5_1.png" style="max-width: 100%;"/> </p>`,
      image: "",
      options: [
        `<p> <img src="images/quiz/ee_ec_1/q5_optA_2.png" style="max-width: 100%;"/> </p>`,
        `<p> <img src="images/quiz/ee_ec_1/q5_optB_3.png" style="max-width: 100%;"/> </p>`,
        `<p> <img src="images/quiz/ee_ec_1/q5_optC_4.png" style="max-width: 100%;"/> </p>`,
        `<p> <img src="images/quiz/ee_ec_1/q5_optD_5.png" style="max-width: 100%;"/> </p>`,
      ],
      answer: "D",
      solution: `<p> <img src="images/quiz/ee_ec_1/q5_sol_6.png" style="max-width: 100%;"/> </p>`,
    },
    {
      marks: 2,
      neg: 0,
      type: "NAT",
      text: `<p>Consider the circuit shown below:</p> <p> <img src="images/quiz/ee_ec_1/q8_1.png" style="max-width: 100%;"/> </p> <p>The power delivered by the unknown element is ________ W.</p>`,
      image: "",
      options: [],
      answer: [421, 425],
      solution: `<p> <img src="images/quiz/ee_ec_1/q8_sol_2.png" style="max-width: 100%;"/> </p> <p> <img src="images/quiz/ee_ec_1/q8_sol_3.png" style="max-width: 100%;"/> </p>`,
    },
    {
      marks: 2,
      neg: 0,
      type: "MSQ",
      text: `<p>Consider the circuit shown below:</p> <p> <img src="images/quiz/ee_ec_1/q10_1.png" style="max-width: 100%;"/> </p> <p>Which of the following is/are correct?</p>`,
      image: "",
      options: [
        `<p> <img src="images/quiz/ee_ec_1/q10_optA_2.png" style="max-width: 100%;"/> </p>`,
        `<p> <img src="images/quiz/ee_ec_1/q10_optB_3.png" style="max-width: 100%;"/> </p>`,
        `<p> <img src="images/quiz/ee_ec_1/q10_optC_4.png" style="max-width: 100%;"/> </p>`,
        `<p> <img src="images/quiz/ee_ec_1/q10_optD_5.png" style="max-width: 100%;"/> </p>`,
      ],
      answer: ["B", "A", "C"],
      solution: `<p> <img src="images/quiz/ee_ec_1/q10_sol_6.png" style="max-width: 100%;"/> </p> <p> <img src="images/quiz/ee_ec_1/q10_sol_7.png" style="max-width: 100%;"/> </p>`,
    },
    {
      marks: 2,
      neg: 0,
      type: "NAT",
      text: `<p>For the circuit shown below:</p> <p> <img src="images/quiz/ee_ec_1/q13_1.png" style="max-width: 100%;"/> </p> <p> <img src="images/quiz/ee_ec_1/q13_2.png" style="max-width: 100%;"/> </p>`,
      image: "",
      options: [],
      answer: [64, 65.8],
      solution: `<p> <img src="images/quiz/ee_ec_1/q13_sol_3.png" style="max-width: 100%;"/> </p>`,
    },
  ]
})
