// =========================================================================
// ESE-CE TEST REGISTRY
// =========================================================================
// Add quizzes/tests for ESE-CE below:


registerTest({
  series: "ce-ese-2026",
  name: "SWT - Solid Mechanics",
  date: "Oct 01, 2026",
  questions: [
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p> A hollow metal tube carries an axial compressive load of 200 kN. The yield stress of the material of the tube is 200 N/mm<sup>2</sup> and factor of safety is 1.6. If outer diameter of the tube is 110 mm, then thickness of the metal tube is: </p>`,
      image: "",
      options: [
        `5.5 mm`,
        `4.8 mm`,
        `6.8 mm`,
        `8.7 mm`,
      ],
      answer: "B",
      solution: `<p>(b)</p> <div> </div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q1_sol_1.png" style="max-width: 100%;"/> </div>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p>The correct shape of shear force diagram for the simply supported beam loaded as shown in figure below is:</p> <div></div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q2_1.png" style="max-width: 100%;"/> </div>`,
      image: "",
      options: [
        `<img alt="" src="/images/quiz/ese-ce-swt-sm/q2_optA_1.png" style="max-width: 100%;"/>`,
        `<img alt="" src="/images/quiz/ese-ce-swt-sm/q2_optB_1.png" style="max-width: 100%;"/>`,
        `<img alt="" src="/images/quiz/ese-ce-swt-sm/q2_optC_1.png" style="max-width: 100%;"/>`,
        `<img alt="" src="/images/quiz/ese-ce-swt-sm/q2_optD_1.png" style="max-width: 100%;"/>`,
      ],
      answer: "A",
      solution: `<p>(a)</p>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p> A cantilever circular shaft of length L and diameter d is subjected to a variable torque <img align="absmiddle" alt="" src="/images/quiz/ese-ce-swt-sm/q3_1.png" style="max-width: 100%;"/> where x is measured from free end of the cantilever and k is a constant. What is the angle of twist at the free end ? The torsional rigidity of the shaft <em>GJ</em> is constant. </p>`,
      image: "",
      options: [
        `<img alt="" src="/images/quiz/ese-ce-swt-sm/q3_optA_1.png" style="max-width: 100%;"/>`,
        `<img alt="" src="/images/quiz/ese-ce-swt-sm/q3_optB_1.png" style="max-width: 100%;"/>`,
        `<img alt="" src="/images/quiz/ese-ce-swt-sm/q3_optC_1.png" style="max-width: 100%;"/>`,
        `<img alt="" src="/images/quiz/ese-ce-swt-sm/q3_optD_1.png" style="max-width: 100%;"/>`,
      ],
      answer: "A",
      solution: `<p>(a)</p> <div> </div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q3_sol_1.png" style="max-width: 100%;"/> </div>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p>An alloy wire of 2.5 mm diameter is wounded around a cylinder. The stress in the wire is limited to 50 MPa. The modulus of elasticity of the alloy is 60 GPa. The required radius of the drum is :</p>`,
      image: "",
      options: [
        `2.5 m (Minimum)`,
        `2.5 m (Maximum)`,
        `1.5 m (Minimum)`,
        `1.5 m (Maximum)`,
      ],
      answer: "C",
      solution: `<p>(c)</p> <div> </div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q4_sol_1.png" style="max-width: 100%;"/> </div> <div> </div>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p> A copper rod is 15 m long at 25°C. The temperature of the rod is the raised to 70°C. The free expansion of the rod is restricted to 5 mm only. The thermal stress produced in the rod (in MPa) is :<br/> [Take α = 16 × 10<sup>–6</sup> /°C and E = 120 GPa] </p>`,
      image: "",
      options: [
        `15.4`,
        `35.4`,
        `25.4`,
        `46.4`,
      ],
      answer: "D",
      solution: `<p>(d)</p> <div> </div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q5_sol_1.png" style="max-width: 100%;"/> </div>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p> The beam section shown in the figure below is subjected to a maximum flexural stress of 75 kg/cm<sup>2</sup> . What is the force induced in the shaded portion of the beam section? </p> <div></div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q6_1.png" style="max-width: 100%;"/> </div>`,
      image: "",
      options: [
        `6250 kg`,
        `7500 kg`,
        `11250 kg`,
        `5000 kg`,
      ],
      answer: "B",
      solution: `<p>(b)</p> <div> </div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q6_sol_1.png" style="max-width: 100%;"/> </div> <div> </div>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p> A copper rod of length 1.2 m is placed at room temperature with a gap of 0.05 mm between the end <em>A</em> and the wall as shown in figure. If the temperature is raised by 50°C then the compressive stress induced in the copper rod is: </p> <div></div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q7_1.png" style="max-width: 100%;"/> </div> <div> [Take α = 17 × 10<sup>–6</sup> °C<sup>–1</sup> and <em>E</em> = 110 GPa]. </div>`,
      image: "",
      options: [
        `75.85 MPa`,
        `88.92 MPa`,
        `64.89 MPa`,
        `92.92 MPa`,
      ],
      answer: "B",
      solution: `<p>(b)</p> <div> </div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q7_sol_1.png" style="max-width: 100%;"/> </div>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p>Maximum shear stress theory (of failure) is also known as:</p>`,
      image: "",
      options: [
        `Beltrami's theory`,
        `Coulomb's theory`,
        `Lame's theory`,
        `Rankine's theory`,
      ],
      answer: "B",
      solution: `<p>(b)</p> <div> </div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q8_sol_1.png" style="max-width: 100%;"/> </div>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p>For materials which do not show a distinct yield point, the term proof stress is defined. While defining proof stress, the permanent deformation is taken as:</p>`,
      image: "",
      options: [
        `0.005`,
        `0.004`,
        `0.002`,
        `0.003`,
      ],
      answer: "C",
      solution: `<p>(c)</p>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p>A hollow circular shaft of internal diameter 20 mm and external diameter 30 mm is subjected to compressive load. The maximum distance of the point of application of load from centre of column section for no tension anywhere in the section is:</p>`,
      image: "",
      options: [
        `14.65 mm`,
        `11.25 mm`,
        `18.52 mm`,
        `5.42 mm`,
      ],
      answer: "D",
      solution: `<p>(d)</p> <div> </div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q10_sol_1.png" style="max-width: 100%;"/> </div>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p> A right angled triangular section with base 60 mm and height 90 mm is subjected to a shear force of 75 kN. The shear stress (in N/mm<sup>2</sup> ) at the centroidal axis of the section is nearly: </p>`,
      image: "",
      options: [
        `27`,
        `45`,
        `37`,
        `30`,
      ],
      answer: "C",
      solution: `<p>(c)</p> <div> </div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q11_sol_1.png" style="max-width: 100%;"/> </div>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p>A 4 m long circular strut is pin-jointed at both the ends. This same strut when used as a simply supported beam gave mid-span deflection of 12 mm under a central point load of 100 N. The critical load for the strut is:</p> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q12_1.png" style="max-width: 100%;"/> </div>`,
      image: "",
      options: [
        `6937.5 N`,
        `3375.5 N`,
        `7937.5 N`,
        `2375.5 N`,
      ],
      answer: "A",
      solution: `<p>(a)</p> <div> </div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q12_sol_1.png" style="max-width: 100%;"/> </div>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p>A simply supported beam of span 6 m is subjected to a clockwise moment of 80 kNm at a distance of 2 m from left end as shown in figure. Which of the following represents its correct SFD ?</p> <div></div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q13_1.png" style="max-width: 100%;"/> </div>`,
      image: "",
      options: [
        `<img alt="" src="/images/quiz/ese-ce-swt-sm/q13_optA_1.png" style="max-width: 100%;"/>`,
        `<img alt="" src="/images/quiz/ese-ce-swt-sm/q13_optB_1.png" style="max-width: 100%;"/>`,
        `<img alt="" src="/images/quiz/ese-ce-swt-sm/q13_optC_1.png" style="max-width: 100%;"/>`,
        `<img alt="" src="/images/quiz/ese-ce-swt-sm/q13_optD_1.png" style="max-width: 100%;"/>`,
      ],
      answer: "A",
      solution: `<p>(a)</p> <div> </div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q13_sol_1.png" style="max-width: 100%;"/> </div>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p>A flitched beam is made of timber and steel as shown in figure. The moment of resistance (in kNm) of the beam is:</p> <div></div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q14_1.png" style="max-width: 100%;"/> </div> <div> [Take σ<sub>T</sub> = 5 MPa and σ<sub>S</sub> = 100 MPa] </div>`,
      image: "",
      options: [
        `18.375`,
        `15.375`,
        `12.375`,
        `20.375`,
      ],
      answer: "A",
      solution: `<p>(a)</p> <div> </div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q14_sol_1.png" style="max-width: 100%;"/> </div> <div> </div>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p>The distance of shear centre from middle of web of channel section of uniform thickness 3 mm with b = 55 mm and h = 200 mm is:</p> <div></div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q15_1.png" style="max-width: 100%;"/> </div>`,
      image: "",
      options: [
        `17.123 mm`,
        `15.375 mm`,
        `12.375 mm`,
        `20.375 mm`,
      ],
      answer: "A",
      solution: `<p>(a)</p> <div> </div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q15_sol_1.png" style="max-width: 100%;"/> </div>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p> Consider the following statements in reference to transformation of stresses:<br/> 1. In case of two like and equal principal stresses, the resultant stress on any plane is equal to the principal stresses.<br/> 2. In case of two equal and unlike stresses, the resultant stress on any plane is equal to principal stresses.<br/> 3. In case of two like and equal principal stresses, the obliquity of the resultant stress is on any plane is zero.<br/> 4. In a strained material subjected to two dimensional stresses, the sum of normal stresses on any two mutually perpendicular planes is equal to the sum of major and minor principal stresses.<br/>Which of the above statements are correct? </p>`,
      image: "",
      options: [
        `1 and 4`,
        `2 and 4`,
        `3 and 4`,
        `All of these`,
      ],
      answer: "D",
      solution: `<p>(d)</p>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p>Which of the following theory is best suited for ductile materials subjected to pure shear ?</p>`,
      image: "",
      options: [
        `Distortion energy theory`,
        `Rankine's theory`,
        `Haigh's theory`,
        `St. Venant's theory`,
      ],
      answer: "A",
      solution: `<p>(a)</p>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p> An overhanging beam is as shown in figure below. The deflection at free end is:<br/>(Assume constant flexural rigidity EI). </p> <div></div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q18_1.png" style="max-width: 100%;"/> </div>`,
      image: "",
      options: [
        `<img alt="" src="/images/quiz/ese-ce-swt-sm/q18_optA_1.png" style="max-width: 100%;"/>`,
        `<div></div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q18_optB_1.png" style="max-width: 100%;"/> </div>`,
        `<img alt="" src="/images/quiz/ese-ce-swt-sm/q18_optC_1.png" style="max-width: 100%;"/>`,
        `<img alt="" src="/images/quiz/ese-ce-swt-sm/q18_optD_1.png" style="max-width: 100%;"/>`,
      ],
      answer: "B",
      solution: `<p>(b)</p> <div> </div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q18_sol_1.png" style="max-width: 100%;"/> </div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q18_sol_2.png" style="max-width: 100%;"/> </div>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p> Consider the following statements:<br/> 1. When a shaft is subjected to torsion, the actual shear stress is developed on the cross - section in the vertical direction.<br/> 2. A horizontal shaft when subjected to torsion, complimentary shear stress gets produced on the longitudinal section having the axis, longitudinally.<br/> 3. When a shaft is subjected to torsion, maximum shear stress occurs at half of the radius measured from the axis of the shaft.<br/> 4. For two equally strong shafts, their polar moduli are also equal.<br/>Which of the above statements are correct? </p>`,
      image: "",
      options: [
        `2 and 4`,
        `1 and 4`,
        `2, 3 and 4`,
        `All statements are correct`,
      ],
      answer: "A",
      solution: `<p>(a)</p>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p> A shaft <em>ABCD </em> is subjected to clockwise torque <em>T</em> at <em>A</em> , an anticlockwise torque 2<em>T</em> at <em>B</em> , an anticlockwise<br/> torque <em>T</em> at <em>C</em> and clockwise torque 2<em>T</em> at <em>D</em> . the maximum torque in the shaft will occur: </p> <div></div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q20_1.png" style="max-width: 100%;"/> </div>`,
      image: "",
      options: [
        `Between <em>C</em> and <em>D</em>`,
        `Between <em>A</em> and <em>B</em>`,
        `Between <em>B</em> and <em>C</em>`,
        `Between <em>A</em> and <em>C</em>`,
      ],
      answer: "A",
      solution: `<p>(a)</p>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p> A structural steel member when subjected to tension has the limit of proportionality as 300 N/mm<sup>2</sup> . The principal stresses in the material are 115 MPa and – 55 MPa. The Poisson's ratio of the material is 0.3. The factor of safety as per maximum strain theory is: </p>`,
      image: "",
      options: [
        `1.15`,
        `3.25`,
        `1.48`,
        `2.28`,
      ],
      answer: "D",
      solution: `<p>(d)</p> <div> </div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q21_sol_1.png" style="max-width: 100%;"/> </div>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p> There is a 2 m long steel rod with slenderness ratio 125. The rod is used as a fixed column. The coefficient of thermal expansion of steel is 12 × 10<sup>–6</sup> °C–1. The rise in temperature required to induce buckling in this column is: </p>`,
      image: "",
      options: [
        `32.55 °C`,
        `45.64 °C`,
        `52.64 °C`,
        `72.65 °C`,
      ],
      answer: "C",
      solution: `<p>(c)</p> <div> </div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q22_sol_1.png" style="max-width: 100%;"/> </div>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p> In a strained material, the principal stresses in x and y directions are 120 MPa (T) and 50 MPa (C).<br/>The normal stress on an inclined plane (the normal of which makes an angle of 30° with x axis) is: </p>`,
      image: "",
      options: [
        `77.5 MPa`,
        `7.5 MPa`,
        `108.6 MPa`,
        `85.6 MPa`,
      ],
      answer: "A",
      solution: `<p>(a)</p> <div> </div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q23_sol_1.png" style="max-width: 100%;"/> </div>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p> A circular shaft of radius <em>R</em> is subjected to torsion To at the free end as shown in figure. If the shaded region resists torque <em>T</em> the ratio of <em>T</em> and <em> T<sub>o</sub> </em> is: </p> <div></div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q24_1.png" style="max-width: 100%;"/> </div>`,
      image: "",
      options: [
        `<img alt="" src="/images/quiz/ese-ce-swt-sm/q24_optA_1.png" style="max-width: 100%;"/>`,
        `<div></div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q24_optB_1.png" style="max-width: 100%;"/> </div>`,
        `<img alt="" src="/images/quiz/ese-ce-swt-sm/q24_optC_1.png" style="max-width: 100%;"/>`,
        `<img alt="" src="/images/quiz/ese-ce-swt-sm/q24_optD_1.png" style="max-width: 100%;"/>`,
      ],
      answer: "D",
      solution: `<p>(d)</p> <div> </div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q24_sol_1.png" style="max-width: 100%;"/> </div>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p>A point in a strained body is subjected to a stress of 170 MPa. The strain matrix at this point is as below:</p> <div></div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q25_1.png" style="max-width: 100%;"/> </div> <div>The bulk modulus (in GPa) of the material is:</div>`,
      image: "",
      options: [
        `10`,
        `20`,
        `50`,
        `30`,
      ],
      answer: "B",
      solution: `<p>(b)</p> <div> </div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q25_sol_1.png" style="max-width: 100%;"/> </div>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p>A rigid weightless bar is supported by two identical rods of same cross - sectional area and same modulus of elasticity as shown in figure.</p> <div></div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q26_1.png" style="max-width: 100%;"/> </div> <div>The force in rod DF is:</div>`,
      image: "",
      options: [
        `34.91 kN`,
        `45.91 kN`,
        `55.85 kN`,
        `25.85 kN`,
      ],
      answer: "A",
      solution: `<p>(a)</p> <div> </div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q26_sol_1.png" style="max-width: 100%;"/> </div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q26_sol_2.png" style="max-width: 100%;"/> </div>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p> Match <strong>List-I</strong> (Material) with List-II (Characteristics) and select the correct answer using the codes given below the lists: </p> <div></div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q27_1.png" style="max-width: 100%;"/> </div>`,
      image: "",
      options: [
        `a`,
        `b`,
        `c`,
        `d`,
      ],
      answer: "B",
      solution: `<p>(b)</p>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p> The diameter of a long water supply pipe is 500 mm. It has to withstand a water head of 75 m. The permissible stress in the pipe material is 25 MPa. The specific weight of water is 10 kN/m<sup>3</sup> . The thickness of pipe required is: </p>`,
      image: "",
      options: [
        `10 mm`,
        `2.5 mm`,
        `7.5 mm`,
        `5 mm`,
      ],
      answer: "C",
      solution: `<p>(c)</p> <div> </div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q28_sol_1.png" style="max-width: 100%;"/> </div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q28_sol_2.png" style="max-width: 100%;"/> </div>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p>Williot Mohr's diagram is used for the assessment of:</p>`,
      image: "",
      options: [
        `Forces in the members of pin jointed truss`,
        `Forces in the members of the rigid truss`,
        `Joint deflection in rigid truss`,
        `Joint deflection in pin jointed truss`,
      ],
      answer: "D",
      solution: `<p>(d)</p>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p> A cantilever beam of non-uniform section is subjected to bending moments as shown in figure.<br/>The magnitude of vertical deflection at free end neglecting self-weight of beam is: </p> <div></div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q30_1.png" style="max-width: 100%;"/> </div>`,
      image: "",
      options: [
        `<img alt="" src="/images/quiz/ese-ce-swt-sm/q30_optA_1.png" style="max-width: 100%;"/>`,
        `<img alt="" src="/images/quiz/ese-ce-swt-sm/q30_optB_1.png" style="max-width: 100%;"/>`,
        `<div></div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q30_optC_1.png" style="max-width: 100%;"/> </div>`,
        `Zero`,
      ],
      answer: "D",
      solution: `<p>(d)</p> <div> </div> <div> </div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q30_sol_1.png" style="max-width: 100%;"/> <img alt="" src="/images/quiz/ese-ce-swt-sm/q30_sol_2.png" style="max-width: 100%;"/> </div>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p>A horizontal bar of uniform cross-section is subjected to the forces as shown in figure. Elastic moduli of sections AB and BC are 1.5E and 0.5E. For what value of force F, the net change in length of bar ABC is zero ?</p> <div></div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q31_1.png" style="max-width: 100%;"/> </div> <div></div>`,
      image: "",
      options: [
        `0.375P`,
        `0.575P`,
        `0.675P`,
        `0.875P`,
      ],
      answer: "A",
      solution: `<p>(a)</p> <div> </div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q31_sol_1.png" style="max-width: 100%;"/> </div> <div> </div>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p> The strain energy stored in the portal frame is:<br/>(EI = constant) </p> <div></div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q32_1.png" style="max-width: 100%;"/> </div>`,
      image: "",
      options: [
        `<img alt="" src="/images/quiz/ese-ce-swt-sm/q32_optA_1.png" style="max-width: 100%;"/>`,
        `<img alt="" src="/images/quiz/ese-ce-swt-sm/q32_optB_1.png" style="max-width: 100%;"/>`,
        `<img alt="" src="/images/quiz/ese-ce-swt-sm/q32_optC_1.png" style="max-width: 100%;"/>`,
        `<img alt="" src="/images/quiz/ese-ce-swt-sm/q32_optD_1.png" style="max-width: 100%;"/>`,
      ],
      answer: "C",
      solution: `<p>(c)</p> <div> </div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q32_sol_1.png" style="max-width: 100%;"/> </div> <div> </div>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p> The principal stresses are shown in the figure below. The value of normal stress (in N/mm<sup>2</sup> ) at a plane inclined at 45° to the principal plane is: </p> <div></div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q33_1.png" style="max-width: 100%;"/> </div>`,
      image: "",
      options: [
        `10`,
        `20`,
        `30`,
        `40`,
      ],
      answer: "A",
      solution: `<p>(a)</p> <div> </div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q33_sol_1.png" style="max-width: 100%;"/> </div>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p> Consider the following statements:<br/> 1. Shear stresses on two mutually normal planes are equal in magnitude and direction.<br/> 2. The sum of normal stresses on mutually normal planes is equal to the sum of principal stresses.<br/>Of the above statements, which is / are true ? </p>`,
      image: "",
      options: [
        `1 only`,
        `1 & 2 both`,
        `2 only`,
        `Neither 1 nor 2`,
      ],
      answer: "C",
      solution: `<p> (c)<br/>Shear stresses on two mutually normal i.e. perpendicular planes are equal in magnitude but opposite in direction. </p>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p> <strong>Statement (I):</strong> Failure theories are the statements that define the criteria of initiation of yielding.<br/> <strong>Statement (II):</strong> Whenever any physical quantity like stress, strain, energy per unit volume etc.<br/>exceeds a critical value, yielding of material initiates. </p>`,
      image: "",
      options: [
        `a`,
        `b`,
        `c`,
        `d`,
      ],
      answer: "A",
      solution: `<p>(a)</p>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p> <strong>Statement (I):</strong> Rate of change of loading intensity is defined as shear force.<br/> <strong>Statement (II):</strong> Algebraic sum of all the forces either on left or right of the section is shear force. </p>`,
      image: "",
      options: [
        `a`,
        `b`,
        `c`,
        `d`,
      ],
      answer: "D",
      solution: `<p>(d)</p>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p> <strong>Statement (I):</strong> In an elastic body, the amount of elastic deformation under a given stress is more in case of tensile stress as compared to compressive stress.<br/> <strong>Statement (II):</strong> All the elastic constants are assumed as same in both tension and compression. </p>`,
      image: "",
      options: [
        `a`,
        `b`,
        `c`,
        `d`,
      ],
      answer: "D",
      solution: `<p> (d)<br/>Statement I is false as elastic deformation under a given stress in an elastic body is considered as same both in tension and compression. Statement II is true. </p>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p> <strong>Statement (I):</strong> Strain is fundamental concept and stress is the derived concept.<br/> <strong>Statement (II):</strong> Strain is dimensionless while stress has dimensions of pressure. </p>`,
      image: "",
      options: [
        `a`,
        `b`,
        `c`,
        `d`,
      ],
      answer: "B",
      solution: `<p> (b)<br/>Both Statement I and Statement II are true but Statement II doesn 't explain the Statement I. </p>`,
    },
  ]
});


registerTest({
  series: "ce-ese-2026",
  name: "SWT - Flow of Fluids, Hydraulic Machines and Hydro Power",
  date: "Oct 01, 2026",
  questions: [
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p> In a converging pipe which is inclined upwards, the velocity <em>V</em> of water varies along its length as </p> <div></div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q1_1.png" style="max-width: 100%;"/> </div> <div> where x (in meters) is measured along the pipe. The pipe rises 0.75 m in 3 m length. Determine the magnitude of pressure gradient (in kN/m<sup>2</sup> /m) at the pipe entrance. [Take g = 10 m/s<sup>2</sup> ]. </div>`,
      image: "",
      options: [
        `4.875`,
        `3.875`,
        `2.875`,
        `1.875`,
      ],
      answer: "C",
      solution: `<p>(c)</p> <div> </div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q1_sol_1.png" style="max-width: 100%;"/> </div>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p>The model of a reservoir is drained in 10 minutes by opening the sluice gate. The time required to empty the corresponding prototype if scale ratio is 1 : 900 will be:</p>`,
      image: "",
      options: [
        `5 hours`,
        `10 hours`,
        `8 hours`,
        `12 hours`,
      ],
      answer: "A",
      solution: `<p>(a)</p> <div> </div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q2_sol_1.png" style="max-width: 100%;"/> </div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q2_sol_2.png" style="max-width: 100%;"/> </div>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p> The pressure drop in a 300 mm diameter pipe which is laid horizontal is 60 kPa in a length of 15 m.<br/>The wall shear stress (in Pa) is: </p>`,
      image: "",
      options: [
        `100`,
        `150`,
        `200`,
        `300`,
      ],
      answer: "D",
      solution: `<p>(d)</p> <div> </div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q3_sol_1.png" style="max-width: 100%;"/> </div>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p> Determine the bulk modulus (in N/cm<sup>2</sup> ) of a liquid which is compressed in volume from 15 <em>lt</em> at 100 N/cm<sup>2</sup> to 10 lt at 210 N/cm<sup>2</sup> . </p>`,
      image: "",
      options: [
        `330`,
        `220`,
        `150`,
        `60`,
      ],
      answer: "A",
      solution: `<p>(a)</p> <div> </div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q4_sol_1.png" style="max-width: 100%;"/> </div>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p> Consider the following statements regarding energy consideration in reference to Bernoulli's principle:<br/> 1. Pitot tube indicates the position of total energy line above any arbitrary datum.<br/> 2. In rotational flow, velocity varies normal to the flow.<br/> 3. The piezometric head in a uniform pipe does not remain constant in the direction normal to the flow for rotational flow.<br/> 4. In a real fluid, the total head varies throughout the normal section in a uniform pipe.<br/>Which of the above statements are correct? </p>`,
      image: "",
      options: [
        `1, 3 and 4`,
        `1, 2 and 4`,
        `2, 3 and 4`,
        `All are correct`,
      ],
      answer: "B",
      solution: `<p> (b)<br/>Statement 3 is incorrect. Piezometric head in a uniform pipe remain constant in a direction normal to flow for rotational flow. </p>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p> Consider the following statements regarding development of boundary layer over a flat plate :<br/> 1. For steady state flow, streamlines shift over the boundary layer in order to compensate the discharge across the section of the plate.<br/> 2. Shape factor obtained for boundary layer flow is dependent of velocity profile.<br/> 3. There exits a momentum deficit at the trailing edge of the plate.<br/> 4. For uniform flow, the streamlines are parallel to the direction of flow.<br/>Which of the above statements are correct? </p>`,
      image: "",
      options: [
        `2, 3 and 4`,
        `1, 2 and 3`,
        `1 and 3`,
        `All are correct`,
      ],
      answer: "D",
      solution: `<p>(d)</p>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p> In case of laminar flow through circular pipe, if <em> R<sub>e</sub> </em> is the Reynold's number of flow and <em>d</em> is the pipe diameter then entrance length required to establish fully developed laminar flow is: </p>`,
      image: "",
      options: [
        `<img alt="" src="/images/quiz/ese-ce-swt-sm/q7_optA_1.png" style="max-width: 100%;"/>`,
        `<img alt="" src="/images/quiz/ese-ce-swt-sm/q7_optB_1.png" style="max-width: 100%;"/>`,
        `<img alt="" src="/images/quiz/ese-ce-swt-sm/q7_optC_1.png" style="max-width: 100%;"/>`,
        `<img alt="" src="/images/quiz/ese-ce-swt-sm/q7_optD_1.png" style="max-width: 100%;"/>`,
      ],
      answer: "C",
      solution: `<p>(c)</p> <div> </div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q7_sol_1.png" style="max-width: 100%;"/> </div>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p>As compared to a streamlined body, a bluff body will have</p>`,
      image: "",
      options: [
        `more pressure drag and more friction drag`,
        `less pressure drag and less friction drag`,
        `more pressure drag and less friction drag`,
        `more friction drag and less pressure drag`,
      ],
      answer: "C",
      solution: `<p> (c)<br/>Bluff body is the one which gives rise to large wakes at the rear end that pressure drag in much higher than the friction drag. </p>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p> While analyzing a general qualitative analogy between the gas dynamics and the open channel flow, which of the following results are correct?<br/> 1. Froude's number is analogous to Mach number.<br/> 2. Water depth is analogous to gas density.<br/> 3. Water depth is analogous to gas pressure.<br/>4. Hydraulic jumps are analogous to gas shock waves. </p>`,
      image: "",
      options: [
        `1, 3 and 4`,
        `1, 2 and 3`,
        `1 and 3`,
        `1, 2 and 4`,
      ],
      answer: "D",
      solution: `<p> (d)<br/>Statement 3 is false. Square of water depth is analogous to gas pressure. </p>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p>The Bernoulli's equation is given in its standard form as:</p> <div></div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q10_1.png" style="max-width: 100%;"/> </div> <div></div> <div> The dimensions of constant <em>C</em> are: </div>`,
      image: "",
      options: [
        `ML<sup>–1</sup> T<sup>–2</sup>`,
        `ML<sup>–1</sup> T<sup>–1</sup>`,
        `ML<sup>–2</sup> T<sup>–2</sup>`,
        `MLT<sup>–2</sup>`,
      ],
      answer: "A",
      solution: `<p>(a)</p> <div> </div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q10_sol_1.png" style="max-width: 100%;"/> </div>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p> Consider the following statements:<br/> 1. Dilatant fluid is shear thickening fluid increasing its resistance with increasing strain rate.<br/> 2. Pseudoplastic fluid is shear thickening fluid and is less resistant to high strain rates.<br/> 3. Rheopectic fluids require a gradually increasing shear stress to maintain a constant strain rate.<br/>Which of the above statements are correct? </p>`,
      image: "",
      options: [
        `2 and 3`,
        `1 and 2`,
        `1 and 3`,
        `All are correct`,
      ],
      answer: "C",
      solution: `<p> (c)<br/>Statement 2 is false. Pseudoplastic fluid is a shear thinning fluid. </p>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p>A limiting combination of source and sink of equal strength which are allowed to approach each other in a manner that the product of their strength and distance between them is constant known as:</p>`,
      image: "",
      options: [
        `Doublet`,
        `Karman Vortex street`,
        `Russell-John Scott street`,
        `Leonhard phenomenon`,
      ],
      answer: "A",
      solution: `<p>(a)</p>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p> Two tanks are connected by parallel pipes <em>A</em> and <em>B</em> . Pipe A has friction factor of f while pipe <em>B</em> has friction factor of 3<em>f</em> . Both pipes have identical lengths. The size of pipe <em>B</em> is twice the size of pipe <em>A</em> . The ratio of discharge through pipe <em>A</em> to that through pipe <em>B</em> is: </p>`,
      image: "",
      options: [
        `<img alt="" src="/images/quiz/ese-ce-swt-sm/q13_optA_1.png" style="max-width: 100%;"/>`,
        `<img alt="" src="/images/quiz/ese-ce-swt-sm/q13_optB_1.png" style="max-width: 100%;"/>`,
        `<img alt="" src="/images/quiz/ese-ce-swt-sm/q13_optC_1.png" style="max-width: 100%;"/>`,
        `<img alt="" src="/images/quiz/ese-ce-swt-sm/q13_optD_1.png" style="max-width: 100%;"/>`,
      ],
      answer: "B",
      solution: `<p>(b)</p> <div> </div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q13_sol_1.png" style="max-width: 100%;"/> </div>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p> Nikuradse's test results are plotted on a logarithmic scale with friction factor <em>f</em> as ordinate and<br/> Reynold's number <em> R<sub>e</sub> </em> as abscissa. Choose the correct statements:<br/> 1. For <em> R<sub>e</sub> </em> &lt;2000, friction factor follows a linear relationship with <em>R<sub>e </sub></em>.<br/> 2. For high values of Re and pipes with very small relative roughness, friction factor is governed by <em> R<sub>e</sub> </em> and thickness of laminar sub-layer.<br/> 3. In rough turbulent flow, <em>f</em> versus <em> R<sub>e</sub> </em> relationship becomes parallel to <em> R<sub>e</sub> </em> axis. </p>`,
      image: "",
      options: [
        `1 and 3`,
        `1 and 2`,
        `2 and 3`,
        `All are correct`,
      ],
      answer: "A",
      solution: `<p> (a)<br/> Statement 2 is false. For high values of <em> R<sub>e</sub> </em> and pipes with very small relative roughness, friction factor is governed by <em> R<sub>e</sub> </em> only. </p>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p>Match List - I (Trajectory) with List - II (Corresponding spin) in reference to Magnus effect which can be used as an advantage in tennis:</p> <div></div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q15_1.png" style="max-width: 100%;"/> </div>`,
      image: "",
      options: [
        `a`,
        `b`,
        `c`,
        `d`,
      ],
      answer: "A",
      solution: `<p>(a)</p>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p>A two-dimensional velocity field is given by:</p> <div></div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q16_1.png" style="max-width: 100%;"/> </div> <div></div> <div> At point <em>A</em> (2, 1, 0), the convective acceleration vector is: </div>`,
      image: "",
      options: [
        `<img alt="" src="/images/quiz/ese-ce-swt-sm/q16_optA_1.png" style="max-width: 100%;"/>`,
        `<img alt="" src="/images/quiz/ese-ce-swt-sm/q16_optB_1.png" style="max-width: 100%;"/>`,
        `<img alt="" src="/images/quiz/ese-ce-swt-sm/q16_optC_1.png" style="max-width: 100%;"/>`,
        `<img alt="" src="/images/quiz/ese-ce-swt-sm/q16_optD_1.png" style="max-width: 100%;"/>`,
      ],
      answer: "D",
      solution: `<p>(d)</p> <div> </div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q16_sol_1.png" style="max-width: 100%;"/> </div>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p>The velocity in a two-dimensional flow field is given by,</p> <div></div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q17_1.png" style="max-width: 100%;"/> </div> <div></div> <div>The magnitude of rotation (in rad/sec) at point (2, 3) is:</div>`,
      image: "",
      options: [
        `9.5`,
        `7.5`,
        `10.5`,
        `8.5`,
      ],
      answer: "C",
      solution: `<p>(c)</p> <div> </div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q17_sol_1.png" style="max-width: 100%;"/> </div>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p> The boundary layer thickness at distance of 1 m from the leading edge of flat plate kept at zero angle of incidence to the flow direction is 3 mm. The velocity outside the boundary layer is 30 m/sec. The boundary layer thickness (in mm) at a distance of 5 m from leading edge is:<br/>[Assume boundary layer is laminar throughout]. </p>`,
      image: "",
      options: [
        `<img alt="" src="/images/quiz/ese-ce-swt-sm/q18_optA_1.png" style="max-width: 100%;"/>`,
        `<img alt="" src="/images/quiz/ese-ce-swt-sm/q18_optB_1.png" style="max-width: 100%;"/>`,
        `<img alt="" src="/images/quiz/ese-ce-swt-sm/q18_optC_1.png" style="max-width: 100%;"/>`,
        `<img alt="" src="/images/quiz/ese-ce-swt-sm/q18_optD_1.png" style="max-width: 100%;"/>`,
      ],
      answer: "B",
      solution: `<p>(b)</p> <p> </p>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p>The discharge in laminar flow through pipe of diameter 50 mm having centerline velocity of 2 m/s is:</p>`,
      image: "",
      options: [
        `<img alt="" src="/images/quiz/ese-ce-swt-sm/q19_optA_1.png" style="max-width: 100%;"/>`,
        `<img alt="" src="/images/quiz/ese-ce-swt-sm/q19_optB_1.png" style="max-width: 100%;"/>`,
        `<img alt="" src="/images/quiz/ese-ce-swt-sm/q19_optC_1.png" style="max-width: 100%;"/>`,
        `<img alt="" src="/images/quiz/ese-ce-swt-sm/q19_optD_1.png" style="max-width: 100%;"/>`,
      ],
      answer: "A",
      solution: `<p>(a)</p> <div> </div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q19_sol_1.png" style="max-width: 100%;"/> </div>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p> What will be the kinematic viscosity of a fluid having density of 1000 kg/m<sup>3</sup> if shear stress at a point in the fluid is 0.25 Nm/m<sup>2</sup> . The velocity gradient at this point being 0.2 sec<sup>–1</sup> . </p>`,
      image: "",
      options: [
        `0.125 stokes`,
        `12.5 stokes`,
        `125 stokes`,
        `1.25 stokes`,
      ],
      answer: "B",
      solution: `<p>(b)</p> <div> </div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q20_sol_1.png" style="max-width: 100%;"/> </div>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p> If <em> V<sub>r</sub> </em> is radial velocity component and <em>V</em> <sub>θ</sub> is tangential velocity component then for steady incompressible two-dimensional flow, the continuity equation in polar co-ordinates is given by, </p>`,
      image: "",
      options: [
        `<img alt="" src="/images/quiz/ese-ce-swt-sm/q21_optA_1.png" style="max-width: 100%;"/>`,
        `<img alt="" src="/images/quiz/ese-ce-swt-sm/q21_optB_1.png" style="max-width: 100%;"/>`,
        `<img alt="" src="/images/quiz/ese-ce-swt-sm/q21_optC_1.png" style="max-width: 100%;"/>`,
        `<img alt="" src="/images/quiz/ese-ce-swt-sm/q21_optD_1.png" style="max-width: 100%;"/>`,
      ],
      answer: "D",
      solution: `<p>(d)</p>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p> A piece of irregularly shaped metal weighs 200 kN in air. When this metal piece is completely submerged in water, it weighs 153 kN. Determine the volume of the metal. Take g = 10 m/s<sup>2</sup> . </p>`,
      image: "",
      options: [
        `2.75 m<sup>3</sup>`,
        `47 m<sup>3</sup>`,
        `4.7 m<sup>3</sup>`,
        `6.7 m<sup>3</sup>`,
      ],
      answer: "C",
      solution: `<p>(c)</p> <div> </div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q22_sol_1.png" style="max-width: 100%;"/> </div>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p> Choose the correct statements for flow occurring from left to right:<br/> 1. If streamlines are straight and diverging then only convective tangential positive acceleration exists.<br/> 2. If streamlines are curved and equidistant then there will be only normal convective acceleration.<br/> 3. If streamlines are curved and converging then both normal and tangential acceleration exist.<br/>4. If streamlines are straight and parallel to each other then there is no acceleration. </p>`,
      image: "",
      options: [
        `1, 2 and 4`,
        `2, 3 and 4`,
        `3 and 4`,
        `1, 2 and 3`,
      ],
      answer: "B",
      solution: `<p> (b)<br/> Statement 1 is false. If streamlines are straight and diverging then only convective tangential<br/>retardation i.e. negative acceleration exists. </p>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p> An open circular cylinder of 20 cm diameter and 90 cm in height contains water up to a depth of 75 cm. At what speed the cylinder should be rotated about its vertical axis so that axial depth of water becomes zero? [Take g = 10 m/s<sup>2</sup> ]. </p>`,
      image: "",
      options: [
        `225 rpm`,
        `325 rpm`,
        `447 rpm`,
        `405 rpm`,
      ],
      answer: "D",
      solution: `<p>(d)</p> <div> </div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q24_sol_1.png" style="max-width: 100%;"/> </div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q24_sol_2.png" style="max-width: 100%;"/> </div>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p>The apparent difference between the hydrostatic force on a container base and weight of the liquid inside the container is known as:</p>`,
      image: "",
      options: [
        `Fluid paradox`,
        `Hydrostatic paradox`,
        `Pressure paradox`,
        `Hydrodynamic paradox`,
      ],
      answer: "B",
      solution: `<p>(b)</p>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p> The least radius of gyration of a ship is 10 m. Its metacentric height is 60 cm. What is the time period of oscillation of the ship? [Take <em>g</em> = 10 m/s<sup>2</sup> ]. </p>`,
      image: "",
      options: [
        `25.65 sec`,
        `19.65 sec`,
        `16.55 sec`,
        `18.95 sec`,
      ],
      answer: "A",
      solution: `<p>(a)</p> <div> </div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q26_sol_1.png" style="max-width: 100%;"/> </div>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p>The inlet and throat diameters of a horizontal venturimeter are 25 cm and 5 cm respectively. The differential heads between the inlet and throat is 16 m while 5% of differential head is lost between the inlet and throat of venturimeter. What is the discharge coefficient of the venturimeter?</p>`,
      image: "",
      options: [
        `0.925`,
        `0.935`,
        `0.975`,
        `0.995`,
      ],
      answer: "C",
      solution: `<p>(c)</p> <div> </div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q27_sol_1.png" style="max-width: 100%;"/> </div>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p> A soap bubble has to sustain an absolute pressure of 101.375 kPa with its diameter being 50 mm.<br/>What is the surface tension at soap - air interface? Take atmospheric pressure 101.325 kPa. </p>`,
      image: "",
      options: [
        `0.5215 N/m`,
        `0.3125 N/m`,
        `1.25 N/m`,
        `0.6125 N/m`,
      ],
      answer: "B",
      solution: `<p>(b)</p> <div> </div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q28_sol_1.png" style="max-width: 100%;"/> </div>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p>A hydraulic press works on which of the following principle?</p>`,
      image: "",
      options: [
        `Archimede's principle`,
        `Bernoulli's theorem`,
        `Pascal's law`,
        `Euler's model law`,
      ],
      answer: "C",
      solution: `<p>(c)</p>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p> A pontoon of 20000 kN is floating in water. A weight of 400 kN is moved through a distance of <em>x </em> meters across the deck of pontoon which tilts the pontoon through an angle of 30°. The metacentric height of pontoon is 2.5 m. What is the distance <em>x</em> ? </p>`,
      image: "",
      options: [
        `80.53 m`,
        `65.18 m`,
        `56.25 m`,
        `72.17 m`,
      ],
      answer: "D",
      solution: `<p>(d)</p> <div> </div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q30_sol_1.png" style="max-width: 100%;"/> </div> <div> </div>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p>Figure below shows a tank full of water. What is the ratio of total pressure force on the bottom of the tank and weight of water in tank? The width of tank is 2.5 m.</p> <div></div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q31_1.png" style="max-width: 100%;"/> </div> <div></div>`,
      image: "",
      options: [
        `4`,
        `3`,
        `5`,
        `2`,
      ],
      answer: "A",
      solution: `<p>(a)</p> <div> </div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q31_sol_1.png" style="max-width: 100%;"/> </div>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p>At 25 °C, what is the minimum diameter of glass tube required in order to keep the capillary height change of water less than 3 mm? The surface tension of water is 0.07 N/m.</p>`,
      image: "",
      options: [
        `7.5 mm`,
        `9.5 mm`,
        `5.5 mm`,
        `11.5 mm`,
      ],
      answer: "B",
      solution: `<p>(b)</p> <div> </div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q32_sol_1.png" style="max-width: 100%;"/> </div>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p>A positive surge of height 0.7 m was found to occur in a rectangular channel of flow depth of water as 2.5 m. The celerity of the surge is nearly:</p>`,
      image: "",
      options: [
        `± 5 m/s`,
        `± 10 m/s`,
        `± 6 m/s`,
        `± 8 m/s`,
      ],
      answer: "C",
      solution: `<p>(c)</p> <div> </div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q33_sol_1.png" style="max-width: 100%;"/> </div>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p> In a turbulent flow, the velocity at pipe centerline is 8 m/s and velocity at 5 cm away from pipe centreline in a 250 mm diameter pipe is 5 m/s. The shear velocity is:<br/>[Take log(125) = 2.097, log(75) = 1.875, log(50) = 1.699]. </p>`,
      image: "",
      options: [
        `2.35 m/s`,
        `4.25 m/s`,
        `1.65 m/s`,
        `6.57 m/s`,
      ],
      answer: "A",
      solution: `<p>(a)</p> <div> </div> <div> <img alt="" src="/images/quiz/ese-ce-swt-sm/q34_sol_1.png" style="max-width: 100%;"/> </div>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p> Consider the Statement (I) and Statement (II) and choose the correct option using the codes given below:<br/> (a) Both Statement (I) and Statement (II) are correct and Statement (II) is the correct explanation of Statement (I).<br/> (b) Both Statement (I) and Statement (II) are correct but Statement (II) is not the correct explanation of Statement (I).<br/> (c) Statement (I) is correct but Statement (II) is incorrect.<br/>(d) Statement (I) is incorrect and Statement (II) is correct. </p> <p> Statement (I): The magnitude of viscous shear stresses in a laminar boundary layer decreases with distance from the leading edge.<br/>Statement (II): As the boudary layer thickness increases downstream, the velocity gradients near the wall decrease in magnitude. </p>`,
      image: "",
      options: [
        `a`,
        `b`,
        `c`,
        `d`,
      ],
      answer: "A",
      solution: `<p>(a)</p>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p> Consider the Statement (I) and Statement (II) and choose the correct option using the codes given below:<br/> (a) Both Statement (I) and Statement (II) are correct and Statement (II) is the correct explanation of Statement (I).<br/> (b) Both Statement (I) and Statement (II) are correct but Statement (II) is not the correct explanation of Statement (I).<br/> (c) Statement (I) is correct but Statement (II) is incorrect.<br/>(d) Statement (I) is incorrect and Statement (II) is correct. </p> <p> Statement (I): Provision of air vessels on the suction and delivery side of the reciprocating pump increases the delivery head of the pump.<br/>Statement (II): Air vessels reduce the acceleration head and makes the discharge uniform. </p>`,
      image: "",
      options: [
        `a`,
        `b`,
        `c`,
        `d`,
      ],
      answer: "B",
      solution: `<p> (b)<br/> Air vessels save lot of work required to be done against the frictional resistance in suction and<br/>delivery pipes and thus, delivery head increases. </p>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p> Consider the Statement (I) and Statement (II) and choose the correct option using the codes given below:<br/> (a) Both Statement (I) and Statement (II) are correct and Statement (II) is the correct explanation of Statement (I).<br/> (b) Both Statement (I) and Statement (II) are correct but Statement (II) is not the correct explanation of Statement (I).<br/> (c) Statement (I) is correct but Statement (II) is incorrect.<br/>(d) Statement (I) is incorrect and Statement (II) is correct. </p> <p> Statement (I): Drag force acts normal to the direction of motion.<br/>Statement (II): Lift force acts normal to the direction of motion. </p>`,
      image: "",
      options: [
        `a`,
        `b`,
        `c`,
        `d`,
      ],
      answer: "D",
      solution: `<p> (d)<br/>Statement (I) is incorrect. Drag force acts parallel to the direction of motion. </p>`,
    },
    {
      marks: 2,
      neg: 0.66,
      type: "MCQ",
      text: `<p> Consider the Statement (I) and Statement (II) and choose the correct option using the codes given below:<br/> (a) Both Statement (I) and Statement (II) are correct and Statement (II) is the correct explanation of Statement (I).<br/> (b) Both Statement (I) and Statement (II) are correct but Statement (II) is not the correct explanation of Statement (I).<br/> (c) Statement (I) is correct but Statement (II) is incorrect.<br/>(d) Statement (I) is incorrect and Statement (II) is correct. </p> <p> Statement (I): Kaplan turbine maintains high efficiency over a wide range of turbine output.<br/>Statement (II): Vanes on the hub of Kaplan turbine are adjustable. </p>`,
      image: "",
      options: [
        `a`,
        `b`,
        `c`,
        `d`,
      ],
      answer: "A",
      solution: `<p> (a)<br/>In Kaplan turbine, vanes are adjustable whose position can be varied with load on the turbine and thus discharge. As the blades are adjusted for the shock entry of flow, high efficiency is maintained over a wide range of turbine output. </p>`,
    },
  ]
});
