import os
import re
import json
from bs4 import BeautifulSoup
import urllib.request
from urllib.parse import urlparse

# Ensure directory exists
output_dir = 'js/questions/test_html_parsed'
os.makedirs(output_dir, exist_ok=True)

with open('test.html', 'r', encoding='utf-8') as f:
    html = f.read()

soup = BeautifulSoup(html, 'html.parser')

img_counter = 1

def process_html_content(tag):
    global img_counter
    # Process MathJax
    for math_script in tag.find_all('script', type='math/tex'):
        math_text = math_script.string.strip()
        math_script.replace_with(f'\\\\( {math_text} \\\\)')
    
    for math_script in tag.find_all('script', type='math/tex; mode=display'):
        math_text = math_script.string.strip()
        math_script.replace_with(f'\\\\[ {math_text} \\\\]')
        
    for math_script in tag.find_all('script', type=re.compile(r'math/tex;.*mode\s*=\s*display.*')):
        math_text = math_script.string.strip()
        math_script.replace_with(f'\\\\[ {math_text} \\\\]')

    # Download and replace images
    for img in tag.find_all('img'):
        src = img.get('src', '')
        if src.startswith('http'):
            try:
                ext = '.png'
                if '.jpg' in src: ext = '.jpg'
                if '.gif' in src: ext = '.gif'
                
                filename = f"img_{img_counter}{ext}"
                local_path = os.path.join(output_dir, filename)
                
                req = urllib.request.Request(src, headers={'User-Agent': 'Mozilla/5.0'})
                with urllib.request.urlopen(req) as response, open(local_path, 'wb') as out_file:
                    out_file.write(response.read())
                    
                img['src'] = f"{output_dir}/{filename}"
                img_counter += 1
            except Exception as e:
                print(f"Failed to download image {src}: {e}")
                
    # Remove MathJax preview spans and frames that are auto-generated by MathJax
    for el in tag.find_all(class_='MathJax_Preview'):
        el.decompose()
    for el in tag.find_all(class_='MathJax_CHTML'):
        el.decompose()
    for el in tag.find_all(class_='MathJax'):
        el.decompose()
    for el in tag.find_all(id=re.compile(r'^MathJax-Element-.*-Frame$')):
        el.decompose()
        
    # Get inner HTML
    content = "".join([str(c) for c in tag.contents]).strip()
    return content

questions_data = []

question_divs = soup.find_all('div', class_='res_question')
print(f"Found {len(question_divs)} questions.")

for div in question_divs:
    q_data = {}
    
    # Meta info
    meta_div = div.find('div', class_='res_qs_meta')
    marks = 1.0
    neg = 0.0
    q_type = 'MCQ'
    
    if meta_div:
        for span in meta_div.find_all('span'):
            text = span.get_text(strip=True).lower()
            if 'award:' in text:
                try: marks = float(text.split(':')[1].strip())
                except: pass
            elif 'penalty:' in text:
                try: neg = float(text.split(':')[1].strip())
                except: pass
            elif 'multiple choice' in text:
                q_type = 'MCQ'
            elif 'multiple select' in text:
                q_type = 'MSQ'
            elif 'numerical' in text:
                q_type = 'NAT'
                
    q_data['marks'] = marks
    q_data['neg'] = neg
    q_data['type'] = q_type
    
    # Text
    text_div = div.find('div', class_='res_question_text')
    
    # options
    options_list = []
    ol = text_div.find('ol') if text_div else None
    if ol:
        for li in ol.find_all('li', recursive=False):
            opt_html = process_html_content(li)
            options_list.append(opt_html)
        ol.extract() # remove options from question text
        
    q_text_html = process_html_content(text_div)
    q_data['text'] = q_text_html
    q_data['options'] = options_list
    q_data['image'] = "" # we keep images inline in text usually
    
    # Answer and solution
    # Note: user html might not have answers in standard format if they are just questions, 
    # but the user said "question options and answers or images".
    ans_str = "A"
    sol_str = ""
    # We try to find answer
    ans_area = div.find('div', class_='res_answer_area')
    if ans_area:
        pass # To be implemented based on actual HTML
        
    q_data['answer'] = ans_str
    q_data['solution'] = sol_str
    
    questions_data.append(q_data)

# Print a sample
if questions_data:
    print("Sample extracted question:")
    print(json.dumps(questions_data[0], indent=2))
